import { regionalLocations } from './regional-locations'
export type LocationPage = {
  slug: string
  name: string
  group: string
  photo: string
  intro: string
  arrival: string
  planning: string
  question: string
  answer: string
  region: string
}
const location = (
  slug: string,
  name: string,
  group: string,
  photo: string,
  intro: string,
  arrival: string,
  planning: string,
  question: string,
  answer: string,
  region = 'Dubai',
): LocationPage => ({
  slug,
  name,
  group,
  photo,
  intro,
  arrival,
  planning,
  question,
  answer,
  region,
})

export const locationPages: LocationPage[] = [
  ...regionalLocations,
  location(
    'dubai',
    'Dubai',
    'The seven emirates',
    'dubai',
    'Choose a rental around the Dubai you plan to visit: a beach resort on the Palm, an apartment in the Marina, meetings in DIFC or a family stay in a residential community. The right delivery point is the address where your trip actually begins.',
    'Select your area below and give the property, entrance and preferred time. For an airport arrival, include DXB or DWC and your flight details. Your confirmed quote sets the meeting point and delivery arrangements.',
    'Compare the live catalogue by model, category and recorded seats. Ask about luggage fit, mileage and parking for your planned route before deciding between a sports car, luxury sedan and SUV.',
    'Can I collect in Dubai and finish my rental in another emirate?',
    'Include both locations in your request. The team will confirm permitted travel, collection timing and any delivery charges before you agree to the rental.',
  ),
  location(
    'abu-dhabi',
    'Abu Dhabi',
    'The seven emirates',
    'abu-dhabi',
    'Plan an Abu Dhabi rental around a Yas Island resort stay, city appointments or a visit to Saadiyat Island. These destinations call for different routes and handover points, so name your actual hotel or address when requesting the car.',
    'For Yas Island, specify the resort entrance and any event-related access information from your host. If arriving by air, identify Zayed International Airport (AUH) and share your flight details with the team.',
    'Choose for the distance, passengers and bags on your itinerary. Staying near Yas Marina Circuit does not authorise taking a rental onto the track; agree the permitted road use and mileage allowance before booking.',
    'Can I request a handover at a Yas Island hotel?',
    'Yes, name the property and the entrance recommended by the hotel. The team must confirm vehicle availability, the handover time and delivery charges for your dates.',
    'Abu Dhabi',
  ),
  location(
    'sharjah',
    'Sharjah',
    'The seven emirates',
    'sharjah',
    'Arrange a car around your Sharjah hotel, coastal break or desert retreat. Specify whether you are staying in Sharjah city or elsewhere in the emirate; the resort name is more useful than a general emirate label for planning delivery.',
    'Share the property address and arrival time. For a desert retreat, confirm a paved, vehicle-accessible meeting point with the resort and request the handover there rather than assuming off-road delivery.',
    'Choose a sedan for city travel or compare SUVs for family luggage. A taller vehicle is not permission for dune driving; the rental must remain within the routes and uses agreed with the team.',
    'Can I use the car for trips between Sharjah and Dubai?',
    'Describe your planned journeys when requesting the quote. The team confirms permitted travel, mileage and return arrangements; allow your own schedule for traffic rather than relying on a fixed journey-time promise.',
    'Sharjah',
  ),
  location(
    'ajman',
    'Ajman',
    'The seven emirates',
    'ajman',
    'Build an Ajman rental around a coastal hotel stay, a family visit or journeys to neighbouring emirates. Choose a car for the passengers and luggage travelling with you, then arrange a handover at the actual resort or residential entrance.',
    'Give the property’s current name and guest entrance. If your hotel reservation uses a previous hotel name, include the address as well so the team can confirm the correct destination.',
    'For a beach stay, check overnight parking and how you will use the car between check-in and departure. Compare a daily rental with the longer-period rates recorded for the model if you plan to keep it throughout the stay.',
    'Can I collect at a Dubai airport and return at my Ajman hotel?',
    'Request both locations, your flight details and the return date. The team reviews the complete trip and confirms any inter-emirate delivery and collection charges.',
    'Ajman',
  ),
  location(
    'umm-al-quwain',
    'Umm Al Quwain',
    'The seven emirates',
    'umm-al-quwain',
    'Plan a rental for a quiet coastal stay in Umm Al Quwain, with the freedom to make road trips beyond the resort. Start with the hotel name, the people travelling and whether the car is needed throughout your stay or only around arrival and departure.',
    'Supply the resort entrance and your preferred collection window. If you have a beach or mangrove activity, arrange the vehicle meeting point on an accessible road or permitted parking area.',
    'Ask about luggage space for beach bags and family belongings. A coastal itinerary does not permit driving on sand or through wetland areas; confirm the car’s agreed use before leaving the road.',
    'Can I arrange collection at Vida Beach Resort Umm Al Quwain?',
    'Include the full property name and arrival time. Confirm a suitable guest entrance with the resort, then ask the team to verify vehicle availability and the delivery quote.',
    'Umm Al Quwain',
  ),
  location(
    'ras-al-khaimah',
    'Ras Al Khaimah',
    'The seven emirates',
    'ras-al-khaimah',
    'Choose a car around your Ras Al Khaimah resort stay, from Al Marjan Island to Al Hamra and the city. The exact property matters when planning delivery, especially if the rental starts in Dubai and finishes at your resort.',
    'Give the resort, emirate and guest entrance with your arrival date. For an island property, confirm its road-accessible meeting point rather than using a generic Al Marjan Island pin.',
    'If your itinerary includes mountain roads, describe the route and ask the team to confirm permitted use and mileage. Check the exact vehicle’s luggage space for the return journey as well as the outbound trip.',
    'Can I request a car at an Al Marjan Island resort?',
    'Yes, name the resort and your preferred handover time. The team confirms availability, delivery cost and return arrangements; hotel parking and access should be checked with the property.',
    'Ras Al Khaimah',
  ),
  location(
    'fujairah',
    'Fujairah',
    'The seven emirates',
    'fujairah',
    'Plan a rental for an east-coast resort stay, a Fujairah city visit or a road journey from Dubai. Identify whether you are staying around Al Aqah, another coastal destination or the city so the handover is planned for the right address.',
    'Provide the resort’s full name and guest entrance. If you are arriving after a longer drive, agree the return or collection window with enough room to complete the inspection.',
    'Compare a comfortable sedan with an SUV for passengers, suitcases and beach equipment. Confirm mileage for the whole route and keep the vehicle within the permitted road use stated in the rental terms.',
    'Can I arrange delivery at a resort in Al Aqah?',
    'Name the actual property and dates in your request. The team will review vehicle availability, delivery timing and charges rather than treating all Fujairah addresses as one meeting point.',
    'Fujairah',
  ),
  location(
    'palm-jumeirah',
    'Palm Jumeirah',
    'Islands & waterfront',
    'palm',
    'Make the Palm your base for beach days, restaurant reservations and trips into the city. Choose a car around the people and luggage travelling with you, then arrange delivery to your hotel or residence.',
    'Specify the hotel entrance or residential building, and whether it is on the trunk, a frond or the crescent. These are different meeting points; a general Palm Jumeirah address is not enough.',
    'Allow time for the journey along the crescent when planning dinner in the city. Compare a convertible for two with an SUV if your stay includes family luggage or a stroller.',
    'Can I collect at one Palm hotel and return at another?',
    'Include both properties and the preferred times in your request. The team will confirm whether the handovers can be arranged and quote any associated delivery charges.',
  ),
  location(
    'jumeirah-beach-residence',
    'Jumeirah Beach Residence (JBR)',
    'Islands & waterfront',
    'marina',
    'Stay close to The Walk and the beach, with a rental car for the parts of Dubai beyond the waterfront. JBR suits visitors who want to combine time on foot with independent drives to restaurants, shops and attractions.',
    'Send the hotel name or the cluster and tower name for an apartment. Agree a vehicle-accessible entrance with the team rather than using a pedestrian beach entrance as your meeting point.',
    'Check parking arrangements with your accommodation before choosing a large SUV. For a couple with light bags, compare a sports car with a luxury sedan; passenger space and luggage space are separate considerations.',
    'Can the car be handed over on The Walk?',
    'The exact handover point must be agreed. Hotel entrances and permitted parking areas are more practical than arranging a meeting on a pedestrian section of the waterfront.',
  ),
  location(
    'dubai-marina',
    'Dubai Marina',
    'Islands & waterfront',
    'marina',
    'A Dubai Marina rental works for apartment stays, marina dining and drives to other parts of the emirate. Pick the model you want to drive, then match the handover to your building or hotel rather than a broad marina pin.',
    'Give the tower name, street entrance and a reachable phone number. If your visit includes a yacht departure, supply the operator’s actual boarding location separately from the accommodation address.',
    'An SUV is useful when passengers bring several suitcases, while a sedan can be easier to plan around a city itinerary. Ask about the luggage fit of the exact model before confirming.',
    'Is Dubai Harbour the same collection point as Dubai Marina?',
    'No. Share the exact hotel, tower or marina entrance you intend to use. A yacht booking may depart from Dubai Harbour or another marina even when the operator describes the trip as a Dubai Marina cruise.',
  ),
  location(
    'business-bay',
    'Business Bay',
    'City & business',
    'dubai',
    'Combine meetings, hotel stays and evenings by the Dubai Water Canal with a car that fits your schedule. Business Bay includes office towers, residences and hotels, so the useful starting point is your building and appointment time.',
    'Include the building name and the visitor or hotel entrance. If you need to leave immediately for a meeting, allow time for the vehicle inspection and rental paperwork before your departure.',
    'Choose a sedan for business travel with a small party, or compare SUVs when colleagues and luggage travel together. Plan the rental around the full working day rather than only the first appointment.',
    'Can I request delivery to an office tower?',
    'You can request an office handover. Provide the building’s access instructions and the meeting point approved by reception or security; the team confirms the arrangement before the booking.',
  ),
  location(
    'downtown-dubai',
    'Downtown Dubai',
    'City & business',
    'dubai',
    'Use a Downtown base for Dubai Mall visits, restaurants and drives across the city. A rental is especially useful when your plans reach beyond the walkable area around your hotel and include several destinations in one day.',
    'Name your hotel or residential tower and its vehicle entrance. Dubai Mall, Burj Khalifa residences and nearby hotels have distinct access points, even when a map places them close together.',
    'Share any fixed dinner or attraction times when arranging collection. Leave time to inspect the car and understand parking, fuel and return requirements before joining the city traffic.',
    'Can I meet at Dubai Mall instead of my hotel?',
    'Request the specific permitted parking or meeting area. The team needs an agreed vehicle-accessible point and cannot confirm a handover from the words “Dubai Mall” alone.',
  ),
  location(
    'dubai-international-airport',
    'Dubai International Airport (DXB)',
    'City & business',
    'dubai',
    'Arrange a rental around your arrival at DXB and keep the car for the rest of your Dubai stay. Select for both passengers and checked bags, then share your flight information so the handover can be planned.',
    'Provide the flight number, arrival date, terminal and a phone number that will work after landing. Confirm the meeting point with the team; do not assume a car is waiting at the arrivals curb.',
    'Allow for immigration and baggage collection before selecting a handover time. On departure, plan time for the return inspection as well as your airline’s check-in requirements.',
    'Does an airport rental include a driver?',
    'The vehicles on this site are offered through a rental enquiry. A driver is not included in the displayed daily rate. If you need a driven transfer, ask the team to confirm whether a separate arrangement is available.',
  ),
  location(
    'dubai-hills-estate',
    'Dubai Hills Estate',
    'Residential stays',
    'hills',
    'Plan a car around a stay in Dubai Hills Estate, shopping at Dubai Hills Mall or visits to friends in the community. A residential address and a mall meeting point call for different handover arrangements.',
    'Supply the sub-community, building or villa number and any guest-access instructions. For a mall meeting, agree the parking entrance and level in advance rather than using a general shopping-centre pin.',
    'Consider your full passenger count for school visits, shopping and family outings. If golf is part of the itinerary, ask the team to check bag space with all required seats in use.',
    'Can I arrange collection after a golf visit?',
    'Include the club or property name and your expected finish time. The handover needs a permitted meeting point, and the quote should cover any change from the original delivery location.',
  ),
  location(
    'al-barsha',
    'Al Barsha',
    'City & business',
    'dubai',
    'Al Barsha is a practical base for shopping, hotel stays and drives to several sides of Dubai. The area covers more than the streets immediately around Mall of the Emirates, so an exact address helps the team plan delivery.',
    'State the Al Barsha district, hotel or building name and entrance. If you are staying in a residence, check visitor parking and any security instructions before choosing the collection time.',
    'A sedan suits a compact city schedule; an SUV gives more options for family trips and shopping bags. Compare the actual vehicle’s seats and luggage arrangement instead of choosing by category alone.',
    'Can I request a car near Mall of the Emirates?',
    'Yes, include your hotel entrance or a specific permitted meeting point. Mall parking rules and hotel access need to be checked separately when arranging the handover.',
  ),
  location(
    'atlantis-the-royal',
    'Atlantis The Royal',
    'Hotels & resorts',
    'palm',
    'Plan a rental for your stay or dining visit at Atlantis The Royal on Palm Jumeirah. A car gives you an independent way to explore Dubai between time at the resort, without tying the rental period to a single restaurant booking.',
    'Specify Atlantis The Royal by name, your arrival time and whether you are a staying guest or visiting for dining. Confirm the appropriate entrance with the property before arranging a handover.',
    'For airport bags and resort luggage, check the exact model’s boot capacity. If the rental is for an evening out, include the return time and the next day’s plans when comparing daily rates.',
    'Is this the same delivery address as Atlantis, The Palm?',
    'No. They are separate properties. Your request should identify Atlantis The Royal explicitly, along with the entrance or meeting point agreed with the hotel.',
  ),
  location(
    'bulgari-resort-dubai',
    'Bulgari Resort Dubai',
    'Hotels & resorts',
    'beach',
    'Arrange a car for a stay at Bulgari Resort Dubai on Jumeirah Bay Island. Plan the vehicle around your city appointments, coastal drives and luggage, with the resort handover treated as part of your rental request.',
    'Tell the team whether you need the hotel, a residence or the yacht-club area. Ask your host to confirm the access point and any arrangements required for an outside vehicle supplier.',
    'A luxury sedan can suit city dining and business appointments, while a convertible is worth comparing for two travellers with light luggage. Confirm the actual luggage fit before choosing.',
    'Can I arrange a handover near the yacht club?',
    'Request the exact location and check access with your host. The resort, marina and residential entrances should not be treated as interchangeable delivery addresses.',
  ),
  location(
    'bluewaters-island',
    'Bluewaters Island',
    'Islands & waterfront',
    'marina',
    'Use a Bluewaters rental for journeys beyond the island’s hotels, restaurants and waterfront paths. Plan collection around your accommodation, then choose a car for the number of people joining your wider Dubai itinerary.',
    'Provide the hotel or residential building and a road-accessible meeting point. The pedestrian connection to JBR is not a vehicle handover location, so use the entrance agreed with your host.',
    'Check guest parking if you plan to keep the car overnight. For a short stay with several passengers, prioritise usable seats and bags over the exterior size of the vehicle.',
    'Can I collect on Bluewaters and return in JBR?',
    'Include both addresses and times. The team can review the two handovers and confirm the delivery charge and return arrangements in the quote.',
  ),
  location(
    'city-walk',
    'City Walk',
    'City & business',
    'dubai',
    'Combine a City Walk apartment or hotel stay with drives to the beach, Downtown and meetings elsewhere in Dubai. The district’s pedestrian spaces make the exact vehicle entrance an important part of arranging your rental.',
    'Name the hotel, residence or building and ask your host which entrance outside vehicles should use. Share a nearby road-accessible point if your destination itself is on a pedestrian street.',
    'If you have an event at Coca-Cola Arena, separate the collection time from the event start. Arrange the return around your actual itinerary rather than assuming a handover in an event crowd.',
    'Can I use the rental for an arena visit?',
    'Include the event date in your request and check parking or access guidance from the venue. The rental covers the vehicle on agreed terms; event parking and tickets are arranged separately.',
  ),
  location(
    'five-palm-jumeirah',
    'FIVE Palm Jumeirah',
    'Hotels & resorts',
    'palm',
    'Arrange a car for your stay at FIVE Palm Jumeirah and plan the days beyond the resort. Compare models for your party size, bags and planned outings, then request a handover that works with hotel access.',
    'Use the full property name and confirm the guest entrance with the hotel. FIVE Palm Jumeirah should not be confused with other FIVE properties in Dubai when supplying a delivery address.',
    'A sports car may suit two travellers with light bags; a luxury sedan or SUV provides more options for a group. Nominate the eligible driver before the booking is confirmed.',
    'Can a friend receive the car for me?',
    'Tell the team who will collect and drive. Collection and driver authorisation must be agreed in advance; a hotel booking in one person’s name does not automatically authorise another driver.',
  ),
  location(
    'w-dubai-the-palm',
    'W Dubai – The Palm',
    'Hotels & resorts',
    'palm',
    'Plan your rental around a stay on the Palm’s western crescent. W Dubai – The Palm is a separate destination from W Dubai – Mina Seyahi, so the full property name matters when coordinating collection.',
    'Provide your arrival date, the property name and the entrance recommended by the hotel. Leave time for the journey along the crescent when setting an onward appointment in the city.',
    'Compare a convertible for a couple’s stay with an SUV for a family itinerary. Ask about luggage space with the roof arrangement or seating configuration you intend to use.',
    'Can the rental start at the airport and finish at W Dubai – The Palm?',
    'Request both points and your flight details. The team will check the arrangements, rental duration and any delivery or collection charges before confirming.',
  ),
  location(
    'burj-khalifa',
    'Burj Khalifa',
    'City & business',
    'dubai',
    'Plan a rental around a residence, appointment or visit at Burj Khalifa. The tower, its hotel and nearby attractions have different visitor arrangements, so identifying the reason for your visit helps establish a useful meeting point.',
    'State whether you need a residential, hotel or attraction meeting point. Supply the entrance information given by your host rather than relying on the tower’s landmark pin.',
    'Allow time between a vehicle handover and a timed attraction reservation. If your day includes shopping and dinner elsewhere, plan the rental for the complete route and the final return.',
    'Can I collect at the At the Top entrance?',
    'That attraction entrance is not automatically a suitable vehicle meeting point. Agree a permitted parking or hotel-access location with the team before the rental is confirmed.',
  ),
  location(
    'armani-hotel-dubai',
    'Armani Hotel Dubai',
    'Hotels & resorts',
    'dubai',
    'Arrange a rental for an Armani Hotel Dubai stay with a handover planned for the hotel in Burj Khalifa. Choose the car for your wider city plans, from business appointments to dining beyond Downtown.',
    'Name Armani Hotel Dubai and ask the hotel which entrance should be used for an outside rental delivery. A general Burj Khalifa or Dubai Mall address does not identify that handover point.',
    'Check luggage needs before choosing a coupe for an airport journey. For meetings with another passenger, compare a luxury sedan’s rear-seat access with the model you are considering.',
    'Is the car rental arranged by the hotel?',
    'You are sending a request to Zavi. The team coordinates the rental with you, and any hotel access or concierge arrangements need to be confirmed with the property.',
  ),
  location(
    'difc',
    'Dubai International Financial Centre (DIFC)',
    'City & business',
    'dubai',
    'Build a DIFC rental around meeting locations, hotel stays and evening reservations. A clear schedule helps you choose an appropriate rental period and leave time for the first handover before work begins.',
    'Provide the office building or hotel and its visitor entrance. If you have several appointments, identify the first collection point separately from the buildings you will visit later.',
    'A luxury sedan is a useful starting point for business travel; an SUV may work better when colleagues carry luggage. Confirm the authorised drivers if your team expects to share the driving.',
    'Can my company be named in the request?',
    'Add the company name and invoicing requirements in the notes. The team will explain the booking and billing arrangements before you agree to the rental.',
  ),
  location(
    'four-seasons-resort-jumeirah',
    'Four Seasons Resort Dubai at Jumeirah Beach',
    'Hotels & resorts',
    'beach',
    'Plan a car for a stay at the Four Seasons beach resort in Jumeirah, with the flexibility to visit Downtown, coastal restaurants and other parts of the city. Match the vehicle to your bags and the people travelling with you.',
    'Use the full resort name so it is not confused with Four Seasons Hotel Dubai International Financial Centre. Confirm the guest entrance and delivery timing with the property.',
    'For a beach stay followed by a flight, compare the luggage space of the exact model. Include the airport return in the request if the rental will not finish at the resort.',
    'Can I return the car at the DIFC Four Seasons instead?',
    'Request the other property by its full name and provide the return time. The team must confirm the separate collection point and any change to the delivery charge.',
  ),
  location(
    'jumeirah-al-naseem',
    'Jumeirah Al Naseem',
    'Hotels & resorts',
    'beach',
    'Arrange a car for a Jumeirah Al Naseem stay and the journeys beyond Madinat Jumeirah. Choose around your city plans and baggage, with a collection time that leaves room for the vehicle inspection.',
    'Name Al Naseem explicitly and use the entrance confirmed by the hotel. Nearby Jumeirah hotels and the souk have their own access points and should not be used as substitute addresses.',
    'A convertible is worth considering for two with light luggage, while an SUV gives more flexibility for family outings. Confirm any child-seat requirement directly with the team before booking.',
    'Can I request delivery while visiting a restaurant?',
    'Include the restaurant, hotel and reservation time. The team needs a permitted meeting point and enough time for the handover; restaurant access alone does not confirm a delivery arrangement.',
  ),
  location(
    'address-sky-view',
    'Address Sky View',
    'Hotels & resorts',
    'dubai',
    'Use an Address Sky View stay as a starting point for drives across Dubai. Plan your car around the day’s appointments and luggage, and distinguish the hotel from similarly named Address properties when requesting delivery.',
    'Provide Address Sky View and the entrance agreed with the hotel or residence host. Include an arrival time and a contact number so the team can coordinate the handover.',
    'If you are combining an attraction visit with a rental, keep the attraction booking time separate from the collection time. Leave room for both access procedures and the car inspection.',
    'Does a Sky Views attraction ticket arrange parking or rental access?',
    'Check those arrangements with the attraction or property. Your Zavi enquiry needs its own agreed vehicle meeting point; the attraction ticket does not confirm a rental handover.',
  ),
  location(
    'jumeirah-bay-island',
    'Jumeirah Bay Island',
    'Islands & waterfront',
    'beach',
    'Plan a rental around a private residence, resort stay or marina visit on Jumeirah Bay Island. Share the exact destination so the team can review access and arrange a handover that suits your host.',
    'Identify the residence, resort or marina entrance and any visitor-access procedure. An island map pin does not establish permission to enter a private property or a suitable place to inspect the vehicle.',
    'Choose a model around your luggage and onward route into the city. If several guests need transport, check the listed seating and confirm baggage fit before settling on a vehicle.',
    'Do you need access instructions for a private villa?',
    'Yes. Include the villa address and ask your host how a rental delivery should be admitted. Avoid sending private identity documents in the enquiry notes.',
  ),
  location(
    'emirates-hills',
    'Emirates Hills',
    'Residential stays',
    'hills',
    'Arrange a rental for a stay or visit in Emirates Hills, with collection planned around the villa and community entrance. A clear address helps the team distinguish the residential destination from nearby hotels and golf facilities.',
    'Include the villa number, community details and visitor-access instructions from your host. Provide a practical arrival window, particularly if the receiving guest will be away from the property.',
    'If your stay includes golf, confirm room for clubs and passengers together. A large exterior does not guarantee every seating and luggage combination will fit, so ask about the exact model.',
    'Can I collect at a nearby golf club instead of the villa?',
    'Name the club and request an agreed meeting point. Confirm any access requirements with the club and include the different return location if the car will finish at the residence.',
  ),
  location(
    'jumeirah-golf-estates',
    'Jumeirah Golf Estates',
    'Residential stays',
    'hills',
    'Plan a rental for a golf visit or residential stay at Jumeirah Golf Estates. Start with how many players, passengers and golf bags will travel together, then compare cars with the right usable space.',
    'Specify the residential sub-community or clubhouse destination. If you have a tee time, arrange collection early enough to complete the handover before your round rather than at the appointment itself.',
    'Ask about boot access and whether folding a rear seat would remove a passenger place you need. Include any longer city or airport journey in the rental schedule.',
    'Will golf bags fit in a sports car?',
    'That depends on the model and bag dimensions. Send the number and approximate size of the bags; do not assume that a two-seat or performance model will accommodate full-size golf equipment.',
  ),
  location(
    'al-barari',
    'Al Barari',
    'Residential stays',
    'hills',
    'Arrange a rental for a villa stay, a visit to friends or a dining plan in Al Barari. The most useful collection details are the specific property and access instructions, followed by the journeys you intend to make.',
    'Provide the villa, building or restaurant and the entrance your host recommends. Tell the team whether collection should happen at a private residence or a visitor-accessible point.',
    'For several days in a residential base, compare a sedan for everyday drives with an SUV for family luggage. Check the parking space and vehicle size if you plan to use a private garage.',
    'Can I request a rental for several weeks in Al Barari?',
    'Choose your dates and ask for a longer-rental quote. Where a weekly or monthly rate is recorded it appears on the vehicle page; the final duration and mileage terms are confirmed by the team.',
  ),
  location(
    'district-one',
    'District One',
    'Residential stays',
    'dubai',
    'Plan a car around a District One residence or property visit in Mohammed Bin Rashid Al Maktoum City. Include the development and building or villa details so the handover is arranged for the right part of the community.',
    'Give the residential address and any guest-access instructions. If you are viewing property, use the meeting location supplied by the agent rather than a general lagoon or development pin.',
    'An SUV can suit family stays and multiple viewings, while a sedan is a useful option for a small party. Set the return time after the final appointment, with room for the inspection.',
    'Can an estate agent arrange the meeting point?',
    'You can include the agent’s agreed meeting location in your request. The rental contract and authorised driver still need to be confirmed directly with the Zavi team.',
  ),
  location(
    'the-world-islands',
    'The World Islands',
    'Islands & waterfront',
    'beach',
    'Arrange a mainland rental for the journeys before or after a World Islands resort stay. The islands are reached by water, so the car portion of the trip needs to connect with your resort’s mainland boarding arrangements.',
    'Ask the resort for the exact mainland departure point and boarding time. Request a vehicle handover at an agreed road-accessible location; a rental car cannot be delivered by road to the islands.',
    'Decide whether you need the car before departure, after your island stay or for both periods. Coordinate luggage and return timing with the boat transfer rather than booking unused rental days by default.',
    'Can I drive the rental car to my World Islands resort?',
    'There is no road connection for a normal car journey to the islands. This page is for mainland car rental linked to your stay. The resort arranges its own water access, which is separate from the vehicle rental.',
  ),
  location(
    'jumeirah-islands',
    'Jumeirah Islands',
    'Residential stays',
    'hills',
    'Choose a rental for a villa stay or visit in Jumeirah Islands, with enough room for your party and plans across Dubai. Community details matter here because a broad area name does not identify the correct residential entrance.',
    'Send the cluster and villa number, or the exact visitor destination. Confirm any access procedure with your host and arrange a meeting point where the car can be inspected safely.',
    'For a family stay, compare an SUV with a sedan based on actual seat and luggage needs. If the car will be kept at a villa, check available parking with the host before selecting a large model.',
    'Is Jumeirah Islands the same as Jumeirah Heights?',
    'No. They are separate named communities. Include the full address in the notes so delivery is planned for the correct property.',
  ),
  location(
    'la-mer',
    'La Mer / J1 Beach',
    'Islands & waterfront',
    'beach',
    'Plan your rental around a beach or dining visit in the Jumeirah waterfront area formerly known for La Mer. Parts of the destination have changed, so a current venue name is more useful than relying on an older map label.',
    'Give the restaurant, beach venue or nearby residence by its current name and confirm its vehicle entrance. Ask the venue about guest parking and arrival arrangements before your visit.',
    'If your plan is a few hours by the beach followed by dinner elsewhere, book for the full itinerary. Keep the car collection and the venue reservation as separate appointments.',
    'Should I write La Mer or J1 Beach in my request?',
    'Include the actual venue and entrance, plus whichever area name appears on your reservation. This avoids confusion between former La Mer locations and current J1 Beach venues.',
  ),
  location(
    'port-de-la-mer',
    'Port de La Mer',
    'Islands & waterfront',
    'beach',
    'Arrange a car for a Port de La Mer apartment stay or waterfront visit. The useful rental plan starts with the residential building, then your trips into Dubai and the place where you want the rental to finish.',
    'Supply the building or residence name and visitor-access instructions. Distinguish a Port de La Mer residential entrance from a beach-club or restaurant entrance elsewhere along the Jumeirah coast.',
    'Check apartment parking before choosing a large SUV. For two travellers, compare a coupe with a sedan if you will also carry airport luggage during the stay.',
    'Can the car be collected from my apartment parking area?',
    'Ask the host whether an outside rental handover is permitted there. Share the access and parking details with the team, which will confirm a suitable meeting point.',
  ),
  location(
    'arabian-ranches',
    'Arabian Ranches',
    'Residential stays',
    'hills',
    'Plan a car for a villa stay, family visit or golf outing in Arabian Ranches. Identify the specific development and community so the rental handover is not arranged for another similarly named Ranches destination.',
    'Include Arabian Ranches 1, 2 or 3 where applicable, followed by the sub-community and villa number. Ask your host about guest access and a suitable place for the inspection.',
    'An SUV can be practical for family luggage and several outings, while a sedan may suit a smaller party. Include airport travel and any golf equipment in the space requirements.',
    'Can I arrange delivery to Arabian Ranches 2 or 3?',
    'Include the full development name and address in the enquiry. The team will review the requested location, timing and delivery charge before confirming.',
  ),
  location(
    'pearl-jumeirah',
    'Pearl Jumeirah',
    'Islands & waterfront',
    'beach',
    'Arrange a rental for a Pearl Jumeirah residence or resort stay, with a car chosen for the journeys beyond the island. Give the property name so the team can coordinate collection with the correct host or entrance.',
    'Specify the villa or resort and provide its access instructions. Pearl Jumeirah is distinct from Palm Jumeirah and Jumeirah Bay Island, so use the full destination name.',
    'For a resort stay, compare luggage space as well as passenger seats. If you plan to return at an airport or another hotel, include that in the original request.',
    'Can I request a car for a Nikki Beach stay?',
    'Name the resort and your preferred handover time. Confirm the suitable guest entrance with the property; the rental is arranged with Zavi and subject to the agreed access and booking terms.',
  ),
  location(
    'tilal-al-ghaf',
    'Tilal Al Ghaf',
    'Residential stays',
    'hills',
    'Plan a rental for a residential stay or property appointment in Tilal Al Ghaf. Your sub-community and villa address are the key details for collection, particularly when meeting a host or agent at a specific property.',
    'Supply the sub-community, property number and visitor-access information. For a viewing, use the actual appointment location supplied by the agent rather than a general development entrance.',
    'Choose around your day’s passenger count and belongings. If several properties are on the schedule, include enough rental time to complete the final viewing and return inspection.',
    'Can I receive the car at a property viewing?',
    'You can request it at an agreed accessible location. Confirm the appointment time and access with your agent, and leave time to complete the rental handover before the viewing begins.',
  ),
  location(
    'wasl-1',
    'Wasl 1',
    'City & business',
    'dubai',
    'Arrange a car for a Wasl 1 apartment stay or a visit near Zabeel Park. Name the residential building so your rental can be delivered to the right entrance rather than a general park or district meeting point.',
    'Include the tower and guest entrance, and ask your host about visitor parking. If meeting near the park, agree a permitted road-accessible location with the team.',
    'A sedan suits a small party moving between city appointments; an SUV is worth comparing for a family with bags. Check parking dimensions with the building if selecting a particularly large vehicle.',
    'Is Wasl 1 the same address as Al Wasl?',
    'No. Wasl 1 is a specific development near Zabeel Park; Al Wasl is a different area. Include the building name and full address in the request.',
  ),
  location(
    'dubai-creek-harbour',
    'Dubai Creek Harbour',
    'Islands & waterfront',
    'creek',
    'Plan a rental around a hotel or apartment stay at Dubai Creek Harbour. Enjoy the waterfront locally and use the car for trips elsewhere in Dubai, with collection tied to your specific building or hotel.',
    'Give the tower or hotel name and its guest entrance. Distinguish Dubai Creek Harbour from older Dubai Creek destinations in Deira or Bur Dubai when sharing your meeting point.',
    'If your day includes both waterfront time and city visits, arrange collection before the first drive. Compare the exact luggage capacity when combining the rental with an airport arrival.',
    'Can I request an evening handover at the waterfront?',
    'Specify a hotel entrance or permitted parking area and the preferred time. The promenade itself is not automatically a suitable vehicle handover point.',
  ),
  location(
    'the-meadows',
    'The Meadows',
    'Residential stays',
    'hills',
    'Arrange a car for a stay with family or friends in The Meadows. A rental can cover everyday trips, city outings and airport journeys, provided the vehicle suits the passengers and bags you plan to carry.',
    'Include the Meadows community number, street and villa number. Ask your host about guest access and provide a contact number for coordinating the arrival.',
    'For a multi-day villa stay, compare the daily and longer-period rates listed for your preferred car. Confirm the mileage allowance for your planned trips before agreeing to the rental.',
    'Can I request delivery before my host gets home?',
    'A person authorised for the handover must be available at the agreed time. Discuss who will receive the car and drive it before the team confirms the booking.',
  ),
  location(
    'the-lakes',
    'The Lakes',
    'Residential stays',
    'hills',
    'Choose a rental for a residential stay in The Lakes, with a collection plan based on the exact community and villa. Match the car to your day-to-day travel and any airport or golf equipment you need to carry.',
    'Provide the sub-community, villa address and visitor-entry instructions from your host. Avoid using a lakeside path or a general community landmark as the only meeting point.',
    'A sedan may suit a couple’s stay, while an SUV offers more options for a family. Ask about the exact seating configuration if you need both several passenger places and large bags.',
    'Can I keep the rental for the whole residential stay?',
    'Enter the complete dates and request the corresponding quote. Extensions need approval, so contact the team before the agreed return time if your stay changes.',
  ),
  location(
    'the-springs',
    'The Springs',
    'Residential stays',
    'hills',
    'Arrange a car for a Springs villa stay or a visit to friends, with enough flexibility for daily drives across Dubai. Start with the specific Springs community and the number of passengers who will use the car.',
    'Include the community number, street and villa. If you prefer a shopping-centre meeting point, identify the exact location and agree a permitted handover area in advance.',
    'For family outings, compare the usable seats and storage with your stroller or shopping needs. Ask the team about any child-seat requirement rather than assuming equipment is included.',
    'Can I change the return point to the airport?',
    'Send the airport, terminal and departure schedule to the team before the return. A change of collection location must be agreed and may affect the final quote.',
  ),
  location(
    'jumeirah-park',
    'Jumeirah Park',
    'Residential stays',
    'hills',
    'Plan a car for a Jumeirah Park villa stay, family visit or property appointment. A clear residential address lets the team coordinate the rental around your host’s access arrangements and your travel schedule.',
    'Provide the district or cluster information, street and villa number. Confirm where the handover can take place and whether visitor access needs to be arranged ahead of time.',
    'An SUV may suit family luggage, while a luxury sedan can be a useful choice for a smaller party. Check private parking space before selecting a long or wide model.',
    'Can I use a community shopping area as the meeting point?',
    'Request the named location and an agreed parking area. The team needs a practical place for the inspection, not simply a pin for the wider community.',
  ),
  location(
    'jumeirah-heights',
    'Jumeirah Heights',
    'Residential stays',
    'hills',
    'Arrange a rental for an apartment stay or visit in Jumeirah Heights. Choose the model around your passengers and travel plans, then identify the building entrance that your host uses for visitors.',
    'Supply the cluster, building and entrance details. Jumeirah Heights should be distinguished from Jumeirah Islands and other similarly named neighbourhoods in the delivery notes.',
    'Ask the host about parking access if the car will stay overnight. For airport travel, consider luggage capacity alongside the number of seats you need.',
    'Can the handover happen in the building car park?',
    'Confirm permission and access instructions with your host. The team will agree a meeting point that allows the vehicle inspection and paperwork to be completed.',
  ),
  location(
    'dubai-south',
    'Dubai South',
    'Residential stays',
    'dubai',
    'Plan a rental for a Dubai South residential stay, work visit or journey linked to Al Maktoum International Airport. The district covers several destinations, so use the actual property or appointment address in your request.',
    'Provide the development, building or villa and the agreed entrance. If the trip is airport-related, specify DWC explicitly so it is not confused with Dubai International Airport (DXB).',
    'Consider the full distances and rental duration for trips between Dubai South and other areas of the city. Confirm the included mileage and any delivery charge before booking.',
    'Does “Dubai airport” identify the right delivery point?',
    'No. Dubai International Airport is DXB, while Al Maktoum International Airport is DWC. Use the airport code, terminal information and flight number in your request.',
  ),
  location(
    'al-sufouh',
    'Al Sufouh',
    'Islands & waterfront',
    'beach',
    'Arrange a car for an Al Sufouh hotel, residence or business visit. A specific address helps separate the coastal destination from nearby Palm Jumeirah, Media City and other places along your route.',
    'Give the property name, entrance and any visitor instructions. If you are meeting near a beach, confirm a permitted parking location rather than expecting delivery on sand or a pedestrian path.',
    'For a mixed work and leisure stay, compare a sedan with an SUV based on bags and colleagues. Keep coastal stops and city appointments within the agreed mileage and rental period.',
    'Can I take the rental onto a beach?',
    'Ask the team about the vehicle’s permitted use and routes. A beach-area delivery does not authorise driving on sand or taking the car off road.',
  ),
  location(
    'al-wasl',
    'Al Wasl',
    'City & business',
    'beach',
    'Plan a rental around an Al Wasl residence, appointment or dining visit. The district contains many different streets and destinations, so the useful handover details are the property name and the entrance you will actually use.',
    'Include the building or villa number, street and a contact number. If you are visiting a restaurant, arrange a collection window with time for the car inspection before your reservation.',
    'A sedan can suit several short city appointments, while an SUV may work better with family luggage. Confirm where you will park if the rental stays at a residence overnight.',
    'Can I request delivery near City Walk?',
    'Name the exact building, hotel or approved meeting point. City Walk and the wider Al Wasl area are not precise enough on their own for a confirmed vehicle handover.',
  ),
]

export const findLocation = (slug: string) => locationPages.find((page) => page.slug === slug)
