import { occasionGuides, type OccasionGuide } from './occasion-guides'
export type OccasionPage = OccasionGuide & {
  slug: string
  name: string
  title: string
  intro: string
  plan: string
  practical: string
  question: string
  answer: string
  categories: string[]
  brands: string[]
  photoCar: string
}
const occasion = (
  slug: string,
  name: string,
  title: string,
  intro: string,
  plan: string,
  practical: string,
  question: string,
  answer: string,
  categories: string[],
  brands: string[],
  photoCar: string,
): OccasionPage => ({
  slug,
  name,
  title,
  intro,
  plan,
  practical,
  question,
  answer,
  categories,
  brands,
  photoCar,
  ...occasionGuides[slug],
})
export const occasionPages: OccasionPage[] = [
  occasion(
    'date-night',
    'Date night',
    'Date-night car rental in Dubai',
    'Make the journey part of your evening, whether you are heading to dinner in DIFC, a waterfront table in Dubai Marina or a show in Downtown Dubai. Choose a car for two around comfort, parking and the time you want to get home.',
    'Share your collection point, dinner or show time and expected return. If you are combining Downtown and the Marina, leave room for the journey between them rather than booking back-to-back reservations.',
    'A convertible suits a light-luggage evening when the weather is comfortable; a coupe or sedan gives you a quieter, air-conditioned journey. If dinner includes alcohol, arrange separate transport or a sober driver approved for the rental.',
    'Can I rent a car just for dinner?',
    'Ask for the rental period you need, but do not assume an hourly rate. The team will confirm the minimum duration, collection time and full price before you reserve.',
    ['Convertible', 'Sports', 'Luxury'],
    ['Porsche', 'Bentley', 'Mercedes-Benz'],
    'bentley-continental-gtc',
  ),
  occasion(
    'romantic-getaways',
    'Romantic getaways',
    'A car for your romantic Dubai getaway',
    'Build a weekend for two around a beach stay on Palm Jumeirah, a quiet Creek Harbour morning or a change of scenery beyond the city. A suitable car leaves room for your bags and makes the journey as relaxed as the stay.',
    'Include both travellers, the overnight address, luggage and any planned day trips. Match collection to check-in and allow for breakfast or a late checkout before deciding when the rental should end.',
    'Choose the car with the roof and luggage space you will actually use. For a retreat reached by an unpaved track, confirm a paved meeting point; an SUV booking does not authorise dune driving or off-road access.',
    'Can we take the car outside Dubai for our getaway?',
    'Describe the destination before booking. The team must confirm permitted travel areas, mileage and return arrangements. Crossing a border or driving off road requires separate approval and is not included by default.',
    ['Convertible', 'Luxury', 'SUV'],
    ['Bentley', 'Range Rover', 'Porsche'],
    'bentley-continental-gtc',
  ),
  occasion(
    'surprise-gifts',
    'Surprise gifts',
    'Give a Dubai driving experience as a surprise',
    "Turn a favourite-car wish into a rental experience for someone you care about. Plan the reveal at a Dubai home, hotel or agreed meeting point, with the recipient's preferred model and the practical rental checks arranged before the day.",
    'Tell us who is paying, who will drive and which contact should receive planning messages. Include the reveal location, a realistic handover window and whether flowers or a separate gift presentation are planned.',
    'The gift is a rental experience, not ownership of the car. Driver eligibility and contract checks still apply. Confirm any decoration with the team and venue, and keep surprises separate from essential safety and rental information.',
    'Can you keep the booking a surprise for the recipient?',
    'Explain your preferred contact arrangements. The team can discuss a discreet planning contact, but the actual driver still needs to complete the required checks. This form does not purchase a gift voucher or guarantee a surprise-delivery service.',
    ['Sports', 'SuperSport', 'Luxury'],
    ['Ferrari', 'Lamborghini', 'Porsche'],
    'lamborghini-huracan-sto',
  ),
  occasion(
    'marriage-proposals',
    'Marriage proposals',
    'Plan the drive for your Dubai proposal',
    'Choose a car for the journey to a proposal dinner, a private terrace or a waterfront meeting in Dubai. The most useful arrangement leaves space for flowers, time for the venue and a simple plan for getting home afterwards.',
    'Share the general venue, collection window and any photographer coordination. Keep sensitive surprise details with the agreed contact rather than adding them to a public message or asking a driver to improvise the plan.',
    'Venue bookings, photography permissions, flowers and proposal styling are separate arrangements. Ask before putting petals, candles, signs or equipment in or on the car. The rental should fit the proposal schedule without depending on an exact traffic time.',
    'Can the car be part of our proposal photographs?',
    'Describe whether the car will be parked or driven, where the photos will be taken and whether equipment will touch it. Both the vehicle owner and venue may need to approve the arrangement.',
    ['Luxury', 'Convertible', 'Sports'],
    ['Bentley', 'Rolls-Royce', 'Porsche'],
    'bentley-continental-gtc',
  ),
  occasion(
    'honeymoons',
    'Honeymoons',
    'Explore Dubai together on your honeymoon',
    'Plan a honeymoon rental for the days between your arrival, hotel stay and outings. A coupe may suit short trips for two, while a luxury sedan or SUV can make more sense when airport luggage and a change of hotels are part of the itinerary.',
    'List your flight arrival if relevant, your first hotel, bag count and any later accommodation. Decide whether to collect the car after resting at the hotel or request an airport handover, then confirm the permitted meeting point.',
    'Check actual luggage capacity before choosing a two-seat car. Hotel upgrades, honeymoon amenities, airport assistance and restaurant bookings are not part of a listed rental rate; arrange those with the relevant provider.',
    'Can we change hotels during a honeymoon rental?',
    'Yes, include both hotel addresses and your proposed final return point in the enquiry. The team will confirm the handover arrangements and any change in collection or delivery charges.',
    ['Luxury', 'Convertible', 'SUV'],
    ['Mercedes-Benz', 'Bentley', 'Range Rover'],
    'mercedes-benz-s580',
  ),
  occasion(
    'engagement-celebrations',
    'Engagement celebrations',
    'A car for your Dubai engagement celebration',
    'Plan the arrival for an engagement dinner, family gathering or photographs in Dubai. Start with the people travelling and the venue entrance, then choose a model with the seating and access that make the day comfortable.',
    'Include the couple, relatives travelling in the same car, outfit or gift bags and the event schedule. For several cars, provide a separate passenger count and driver for each rather than assuming one reservation covers the party.',
    'A sedan can help with rear-seat access; an SUV may be useful for more bags. Ask the venue about its approved arrival area and get permission for decorations. Chauffeurs and event coordination are separate services to confirm.',
    'Can we arrange cars for both families?',
    'Send the number of cars, guests and intended drivers with the timings. Availability and terms are checked for each vehicle; submitting one enquiry does not reserve a fleet.',
    ['Luxury', 'Sedan', 'SUV'],
    ['Rolls-Royce', 'Bentley', 'Mercedes-Benz'],
    'rolls-royce-phantom',
  ),
  occasion(
    'family-days-out',
    'Family days out',
    'Choose a car for a family day out in Dubai',
    'Build a Dubai day out around the people, pushchairs and bags coming with you. Compare vehicles for a Creek Harbour walk, a beach visit or an attraction booking, using confirmed seat count and luggage space rather than the size of the car in a photograph.',
    'Share the number of adults and children, the child-seat requirements, pushchair size and the first destination. Allow a break between outings and choose a collection time that leaves room for the handover and fitting approved child restraints.',
    'A seven-seat listing does not guarantee room for a full set of large bags with every seat in use. Ask the team to confirm the exact seating configuration and suitable child restraints before booking.',
    'Can you provide child seats for our family rental?',
    "Request the number of seats and each child's age and size so the team can confirm a suitable option, fitting arrangements and any charge. Child seats are not automatically included in the displayed daily rate.",
    ['SUV', 'Luxury'],
    ['Cadillac', 'Range Rover', 'Mercedes-Benz'],
    'cadillac-escalade',
  ),

  occasion(
    'weddings',
    'Weddings',
    'A car for your wedding day',
    'Choose a wedding-day car around the people travelling, the ceremony schedule and the photographs you want to make. Compare the actual model, interior and access before requesting a quote for your date.',
    'Share the preparation address, ceremony and reception venues, passenger count and the time you need to leave each location. Allow time for the handover before the first arrival, especially if the car is also part of your photography schedule.',
    'Check rear-seat access and room for formal clothing. Decorations, commercial photography and any additional driver need approval in advance. A displayed daily rental rate does not include a chauffeur or a wedding package.',
    'Can the wedding car be decorated?',
    'Describe the proposed ribbons, flowers or fittings before booking. Get written approval for any attachment to the vehicle, and confirm who will fit and remove it without damaging the paint or interior.',
    ['Luxury', 'Sedan'],
    ['Rolls-Royce', 'Bentley', 'Mercedes-Benz'],
    'rolls-royce-phantom',
  ),
  occasion(
    'test-drives',
    'Test drives & trial rentals',
    'Spend time with the model you want to drive',
    'A rental can help you experience a model over ordinary journeys before deciding what suits you. Look at the actual vehicle’s seats, controls, driving position and luggage capacity, then request a rental period that gives you useful time with it.',
    'Tell the team which model interests you, whether you want to compare more than one car and your intended dates. Any separate vehicle needs its own availability check and agreed handover.',
    'This is a paid rental enquiry, not a promise of a free dealership test drive. Licence eligibility, deposit, mileage and insurance terms apply. Track use, performance testing and off-road driving are not included in an ordinary road rental.',
    'Can I try a car before deciding to buy one elsewhere?',
    'Explain that purpose when you enquire. The team can confirm a normal rental if the vehicle and terms are suitable; Zavi does not promise a sales inspection, purchase advice or a free trial.',
    ['Sports', 'SuperSport', 'Luxury'],
    ['Porsche', 'Mercedes-Benz', 'BMW', 'Lamborghini'],
    'porsche-911-turbo-s',
  ),
  occasion(
    'corporate-events',
    'Corporate events',
    'Arrive ready for the occasion',
    'Plan corporate-event travel around the people, luggage and appointments that need to move together. Compare a luxury sedan for a small delegation with an SUV for a larger party, using the vehicle’s recorded seating as your starting point.',
    'Include the event venue, arrival window, hotel or office collection point and the number of attendees. For several cars, send the vehicle quantities and timings so availability can be reviewed together.',
    'Specify company billing requirements and authorised drivers early. Venue access, parking passes and any additional transport service must be arranged and confirmed separately from the listed vehicle rate.',
    'Can I request several cars for one company event?',
    'Yes, describe the quantities, preferred models, drivers and schedule in the enquiry notes. The team confirms each vehicle and the overall terms; one reservation request does not guarantee a multi-car booking.',
    ['Luxury', 'Sedan', 'SUV'],
    ['Mercedes-Benz', 'BMW', 'Audi', 'Bentley'],
    'mercedes-benz-s580',
  ),
  occasion(
    'airport-transfers',
    'Airport arrivals & transfers',
    'Your arrival, with the right car waiting by arrangement',
    'Plan a rental for the road journey after your flight and the days that follow. Choose a vehicle that fits your passengers and checked bags, then request an airport handover with the terminal and flight details included.',
    'State DXB or DWC, your flight number, date and a contact number that will work in the UAE. Allow time for immigration and baggage collection, and confirm a permitted meeting point with the team.',
    'The listed prices are vehicle rental rates. A chauffeur, terminal meet-and-greet or driven transfer is not automatically included. If that is what you need, ask the team to confirm a separate service before making travel plans.',
    'What if my flight is delayed?',
    'Contact the team as soon as your arrival changes. The collection time and any waiting or rescheduling terms must be agreed; this website does not promise automatic flight monitoring.',
    ['SUV', 'Sedan', 'Luxury'],
    ['Mercedes-Benz', 'Cadillac', 'BMW', 'Range Rover'],
    'cadillac-escalade',
  ),
  occasion(
    'music-videos',
    'Music videos',
    'Choose the car for your production',
    'Plan a vehicle request around the creative brief, filming location and time on set. Browse the actual car photographs and model details, then explain how the vehicle will appear in the production before agreeing to hire it.',
    'Provide the shoot date, locations, production contact, required hours and whether scenes involve a parked or moving car. Describe any cameras, lighting, props or equipment intended to touch the vehicle.',
    'A standard road rental does not automatically permit commercial filming, stunts, rigging or track use. Obtain the owner’s approval and any location or filming permits before confirming the production schedule.',
    'Can we mount a camera or lighting rig on the car?',
    'Submit the rigging method and intended use for approval before booking. Do not attach equipment or alter the car without written permission and agreed responsibility for the vehicle.',
    ['SuperSport', 'Sports', 'Luxury'],
    ['Lamborghini', 'Ferrari', 'McLaren', 'Rolls-Royce'],
    'lamborghini-revuelto',
  ),
  occasion(
    'photoshoots',
    'Photoshoots',
    'A car that belongs in the frame',
    'Choose a photoshoot vehicle from the model and colour shown in its gallery. Match the request to the styling, location and time you need, then confirm that the specific photographed vehicle is available for the intended use.',
    'Share a short shoot brief, the date, start and finish times, venue and photographer contact. Explain whether the car will remain parked or be driven between locations, and whether the images are commercial.',
    'Check permission from the vehicle owner and the location operator. Props, temporary branding, costume materials and anything placed on the bodywork or interior should be discussed before the shoot.',
    'Can I book a particular exterior colour?',
    'Refer to the actual photographs on the vehicle page and describe the colour in your enquiry. The team must confirm the specific vehicle; a model name alone does not reserve a colour.',
    ['Sports', 'SuperSport', 'Convertible'],
    ['Ferrari', 'Lamborghini', 'Porsche', 'McLaren'],
    'ferrari-f8-spyder',
  ),
  occasion(
    'bachelor-bachelorette-parties',
    'Bachelor & bachelorette celebrations',
    'Plan the drive around the celebration',
    'Choose cars for the people attending and the venues on your celebration itinerary. A sports car can suit a couple, while a sedan or SUV may be more useful when friends need to travel together with belongings.',
    'Provide the date, venue sequence, passenger count and intended drivers. For more than one vehicle, ask the team to check the whole request and confirm each car rather than relying on a single listing.',
    'Every driver must be approved under the rental terms. If plans include alcohol, arrange a sober authorised driver or separate transport. Passenger limits and agreed vehicle use still apply during a celebration.',
    'Can several friends take turns driving?',
    'Only drivers approved for the rental may drive. Share the intended drivers before confirmation and ask the team about additional-driver requirements and charges.',
    ['SUV', 'Luxury', 'Convertible'],
    ['Mercedes-Benz', 'Range Rover', 'Lamborghini', 'Bentley'],
    'mercedes-benz-g-63-brabus',
  ),
  occasion(
    'birthdays',
    'Birthdays',
    'Make the birthday drive part of the day',
    'Plan a birthday rental around the model the recipient wants to experience and the people joining them. Choose from the real vehicle gallery, then request the date, collection point and rental duration that fit the celebration.',
    'Tell the team who is booking, who will receive the car and who will drive. For a surprise, discuss contact arrangements without leaving the eligible driver out of the required rental checks.',
    'Check age and licence eligibility before organising a surprise involving driving. If you want balloons, flowers or decorations, ask for approval before anything is attached to or placed inside the car.',
    'Can I book a birthday car for someone else?',
    'Explain the arrangement in your enquiry. The team needs to approve the actual driver and contract details; paying for a rental does not automatically make another person eligible to drive.',
    ['Sports', 'SuperSport', 'Convertible'],
    ['Lamborghini', 'Ferrari', 'Porsche', 'McLaren'],
    'lamborghini-huracan-sto',
  ),
  occasion(
    'anniversaries',
    'Anniversaries',
    'A drive for a day worth remembering',
    'Build an anniversary rental around your dinner, hotel stay or day out together. Compare a convertible for light luggage with a luxury coupe or sedan when comfort and space matter more to your plans.',
    'Include the collection address, restaurant or hotel schedule and your preferred return time. If the day includes a resort stay, check whether the car will be kept overnight or returned before check-in.',
    'Ask about luggage space, the actual interior and any decorations you would like to use. Confirm the whole rental period, including the following morning if your plans finish late.',
    'Can I return the car at the hotel after dinner?',
    'Request the hotel, entrance and expected time. The team will confirm whether collection can be arranged there and include the applicable timing and delivery terms in the quote.',
    ['Convertible', 'Luxury', 'Sports'],
    ['Bentley', 'Porsche', 'Ferrari', 'Rolls-Royce'],
    'bentley-continental-gtc',
  ),
  occasion(
    'yacht-parties',
    'Yacht parties',
    'Plan the road journey to your yacht departure',
    'Arrange a rental for the journey to the marina and the parts of your day on land. Choose for the guests and bags travelling in the car, then coordinate the road schedule with the yacht operator’s boarding information.',
    'Provide the exact marina, operator, boarding point and departure time. Dubai Marina and Dubai Harbour are different meeting locations; leave enough time to park and reach the agreed boarding point.',
    'Confirm guest parking and whether you will retain the car during the cruise. A yacht charter, marina access and any onward driven transport are separate from the rental car request.',
    'Can the car be delivered directly beside the yacht?',
    'Marina access and permitted vehicle areas vary. Ask the operator for a road-accessible meeting point and have the team confirm it before planning the handover.',
    ['Luxury', 'SUV', 'Convertible'],
    ['Bentley', 'Mercedes-Benz', 'Range Rover', 'Rolls-Royce'],
    'rolls-royce-cullinan',
  ),
  occasion(
    'graduations',
    'Graduations',
    'A car for the ceremony and the plans after it',
    'Plan a graduation rental around the ceremony, family photographs and the celebration afterwards. Start with the number of relatives travelling together and the room needed for formal clothing and belongings.',
    'Share the campus or event venue, ceremony time, authorised driver and passenger count. Arrange collection before the venue arrival window so there is time for the inspection and paperwork.',
    'Check campus parking and visitor access with the organiser. The graduate’s age and licence eligibility must be confirmed if they intend to drive; a celebration does not change the rental requirements.',
    'Can we include photographs with the car at the venue?',
    'Ask the venue about photography and vehicle access, and describe any organised shoot to the rental team. Keep the activity within the vehicle’s agreed use and the venue’s permissions.',
    ['Sedan', 'SUV', 'Luxury'],
    ['Mercedes-Benz', 'BMW', 'Bentley', 'Cadillac'],
    'mercedes-benz-s580',
  ),
  occasion(
    'staycations',
    'Staycations',
    'Choose the car for your resort escape',
    'Plan a staycation rental around the resort, the people travelling and what you want to do beyond the hotel. A convertible may suit two with light bags; an SUV can be more practical when family luggage comes along.',
    'Include the resort and emirate, check-in date, collection point and the return plan. Decide whether the car is needed for the whole stay or only for journeys at the start and end.',
    'Check overnight parking with the resort and confirm the mileage allowance for any excursions. If the trip crosses emirates, include the intended destinations so delivery and return arrangements are clear.',
    'Can I take the car to a resort outside Dubai?',
    'Tell the team the emirate, resort and route you intend to use. The booking must confirm permitted travel, the mileage allowance and any collection arrangements before you leave.',
    ['SUV', 'Convertible', 'Luxury'],
    ['Range Rover', 'Porsche', 'Mercedes-Benz', 'Bentley'],
    'range-rover-vogue-sv',
  ),
  occasion(
    'weekend-road-trips',
    'Weekend road trips',
    'Make room for the journey',
    'Choose a car for the route, passengers and luggage on your weekend itinerary. Compare a comfortable sedan with an SUV based on the journeys you actually plan, rather than assuming every rental category permits every kind of driving.',
    'Share the emirates, overnight stop, approximate route and total rental dates. Ask about the mileage allowance and any travel restrictions before confirming a longer journey.',
    'A normal road rental does not include dune driving, off-road trails, track use or crossing an international border. Check the agreed use, roadside-contact procedure and return plan with the team.',
    'Can I take a road trip to Oman?',
    'Do not assume cross-border travel is permitted. Ask the team before booking; written permission, vehicle eligibility and any required documents would need to be confirmed separately.',
    ['SUV', 'Sedan', 'Luxury'],
    ['Range Rover', 'Mercedes-Benz', 'BMW', 'Porsche'],
    'range-rover-sport',
  ),
  occasion(
    'hotel-guests',
    'Hotel guest rentals',
    'A car for the days beyond your hotel',
    'Arrange a rental that fits your hotel stay and the places you want to explore independently. Start with the real property name, your bags and the number of travellers, then choose a model from the catalogue.',
    'Provide the hotel, arrival date, guest entrance and a reachable contact number. If you are changing hotels, include both properties and discuss whether the return point should change too.',
    'Confirm guest parking with the hotel and allow time for the handover before your first outing. A room booking does not automatically include car rental or permission for a supplier to enter private areas.',
    'Can the hotel concierge coordinate with Zavi?',
    'You can ask your concierge to help identify a suitable meeting point. The car, authorised driver, price and rental terms still need to be confirmed with the Zavi team.',
    ['Luxury', 'SUV', 'Sedan'],
    ['Mercedes-Benz', 'BMW', 'Range Rover', 'Bentley'],
    'mercedes-benz-s580',
  ),
  occasion(
    'real-estate-viewings',
    'Real estate viewings',
    'A car for a full day of property visits',
    'Plan property-viewing travel around the neighbourhoods, appointments and people who need to travel together. Compare a sedan for a small party with an SUV when several clients or family members are joining.',
    'Share the first meeting point, the day’s districts and the final return location. Ask the agent for building or community access instructions, particularly for private villa appointments.',
    'Leave time between viewings for parking and visitor access. If an agent or colleague will drive, confirm that person as an authorised driver before the rental starts.',
    'Can I extend the rental if the viewing schedule changes?',
    'Contact the team before the agreed return time. Extensions depend on vehicle availability and approval, and the revised price and return arrangements must be confirmed.',
    ['SUV', 'Sedan', 'Luxury'],
    ['Mercedes-Benz', 'Range Rover', 'BMW', 'Audi'],
    'range-rover-sport',
  ),
]
export const findOccasion = (slug: string) => occasionPages.find((page) => page.slug === slug)
